Springdata
studio2faces/foodcounter pull request #15
Opened 2020-09-09 15:19 UTC by studio2faces

Spring Data + Lombok + Logback changes

2020-09-09 19:18 UTC, sergeevik requested changes

2020-09-09 19:18 UTC, sergeevik commented on src/main/java/org/s2f/mb/controllers/AuthController.java
> +    public UserService userService;
атрибуты лучше делать приватными

2020-09-09 19:18 UTC, sergeevik commented on src/main/java/org/s2f/mb/controllers/AuthController.java
> +            log.error("Login is null.", e);
давай вместо отлова ошибки вынесем в if, который проверит логин

2020-09-09 19:18 UTC, sergeevik commented on src/main/java/org/s2f/mb/controllers/AuthorizationFilter.java
> +        } catch (NullPointerException e) {
опять же лучше в нужном месте проверить через if

2020-09-09 19:18 UTC, sergeevik commented on src/main/java/org/s2f/mb/controllers/FridgeController.java
> +    public ProductService productService;
private

2020-09-09 19:18 UTC, sergeevik commented on src/main/java/org/s2f/mb/model/entity/Product.java
> +@Transactional
транзакции ставятся над сервисами, чтобы обеспечить атомарность операции

2020-09-09 19:18 UTC, sergeevik commented on src/main/java/org/s2f/mb/service/UserService.java
> +        } else return new User(login);
1. не в 1 строчку

2020-09-09 19:18 UTC, sergeevik commented on src/main/java/org/s2f/mb/service/ProductService.java
> +            return null;
у тебя null улетает наверх, не стоит так делать, если не нашла что искала лучше кинуть ошибку.

2020-09-09 19:18 UTC, sergeevik commented on src/main/java/org/s2f/mb/controllers/AuthController.java
> +            userDb = userService.findByLogin(login);
findByLogin ожидается что он будет искать по логину и только, но ты там ещё возвращаешь нового пользователя. Немного не по канону.
Предполагается, что дао слой возвращает только то, что есть в БД, для бизнес логики слой сервисов

2020-09-10 07:06 UTC, studio2faces commented on src/main/java/org/s2f/mb/controllers/AuthController.java
> +    public UserService userService;
Сделала. Немного затупила )

2020-09-10 07:06 UTC, studio2faces commented on src/main/java/org/s2f/mb/controllers/FridgeController.java
> +    public ProductService productService;
Сделала

2020-09-10 07:07 UTC, studio2faces commented on src/main/java/org/s2f/mb/service/UserService.java
> +        } else return new User(login);
Сделано

2020-09-10 07:37 UTC, studio2faces commented on src/main/java/org/s2f/mb/controllers/AuthController.java
> +            log.error("Login is null.", e);
Сделала

2020-09-10 07:38 UTC, studio2faces commented on src/main/java/org/s2f/mb/model/entity/Product.java
> +@Transactional
Сделано

2020-09-10 07:44 UTC, studio2faces commented on src/main/java/org/s2f/mb/controllers/AuthorizationFilter.java
> +        } catch (NullPointerException e) {
Сделано

2020-09-10 07:55 UTC, studio2faces commented on src/main/java/org/s2f/mb/controllers/AuthController.java
> +            userDb = userService.findByLogin(login);
Сделала

2020-09-10 08:04 UTC, studio2faces commented on src/main/java/org/s2f/mb/service/ProductService.java
> +            return null;
Сделала, забыла как try-catch работает )

2020-09-10 08:48 UTC, merged